### ISSUE TITLE
Improve Docs (README)

### ISSUE THREAD

**Issue by AtmegaBuzz** [AtmegaBuzz/BookCab#16]
Improve by adding 
- all images in 1 section 
- more polished info regarding about section
- Help with grammatical errors.
- setup docs local 
- setup docs using docker  and docker compose
- testing the application

**Comment by Kd-Here** [comment]
Hello Swapnil can I help you with this PR.
Let me know what are your needs.
I will provide a PR with above requirements do you need some more?

**Comment by AtmegaBuzz** [comment]
Hey @Kd-Here Thankyou for helping. Add a section of docker setup with heading and in that write how to setup using docker. It will be standard docker and docker compose install like docker-compose build then up like that

**Comment by AtmegaBuzz** [comment]
And if possible make the images smaller and remove the heading above the images. 2 images should be side by side in a stack

**Comment by Kd-Here** [comment]
Honestly I am not used docker before in project but have an idea we can create container with it.
Can you please give me 1 day time. I will do some research then you can assign it.

**Comment by AtmegaBuzz** [comment]
actually ive already setup the docker container. yo have to just write how to run the app using it 
## Setup using docker 
- For docker run ```docker build .```
- for docker compose run ```docker-compose up ``` 
you have to write this. Feel free to ask anything or need any help

**Comment by Kd-Here** [comment]
Swapnil did my pr was merge.
Bcoz still my profile is showing open issue

**Comment by AtmegaBuzz** [comment]
Ya I have merged the pr. But this issue contains multiple issues in it. So youve solved 1 of it. Rest are still remaining

**Comment by AtmegaBuzz** [comment]
And also when submitting the pr add the issue number like #16 you can see the issue id next to the issue. Edit your pr and add im description fix docker #16

**Comment by ailinedominey** [comment]
@AtmegaBuzz I'd like to help with this doc.

**Comment by AtmegaBuzz** [comment]
Hey @ailinedominey Thankyou for your great pr. I think that's all for the docs issue. I can now close it. If you know little bit of python and want to contribute to the project then your most welcome and let me know if you need any help.

**Comment by ailinedominey** [comment]
Happy to keep contributing to any documentation-related needs/issues as they arise.
